# Generated by Django 4.1.6 on 2023-02-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0002_rename_numerologyresult_destinynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.PositiveIntegerField()),
                ('text_result', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numerology.numerologycategory')),
            ],
        ),
    ]
