# Generated by Django 4.1.6 on 2023-03-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0004_pithagorfirstline_pithagorsecondline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pithagorfirstline',
            name='condition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pithagorsecondline',
            name='condition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pithagorthirdline',
            name='condition',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
