# Generated by Django 4.1.6 on 2023-03-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0005_pithagorfirstline_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PithagorFirstColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.PositiveIntegerField(default=0)),
                ('text_result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PithagorSecondColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.PositiveIntegerField(default=0)),
                ('text_result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PithagorThirdColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.PositiveIntegerField(default=0)),
                ('text_result', models.TextField()),
            ],
        ),
    ]
