# Generated by Django 4.1.6 on 2023-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0006_pithagorfirstcolumn_pithagorsecondcolumn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PithagorAscendingDiagonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.PositiveIntegerField(default=0)),
                ('text_result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PithagorDescendingDiagonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.PositiveIntegerField(default=0)),
                ('text_result', models.TextField()),
            ],
        ),
    ]
